/**
 * Design Template - Code-rendered, never free-form
 */

import type { DesignSchema } from "../schemas/design";

export function renderDesign(data: DesignSchema): string {
  const modulesSection = data.modules.length > 0
    ? data.modules.map((m, i) => {
        const deps = m.dependencies.length > 0
          ? m.dependencies.join(", ")
          : "无";
        const interfaces = m.interfaces.length > 0
          ? m.interfaces.map((iface) => `- \`${iface}\``).join("\n")
          : "- 待定";
        return `### ${i + 1}. ${m.name}

**职责**：${m.responsibility}

**接口**：
${interfaces}

**依赖**：${deps}`;
      }).join("\n\n")
    : "待补充";

  const decisionsSection = data.decisions.length > 0
    ? data.decisions.map((d) => `- **${d.decision}** — ${d.rationale}`).join("\n")
    : "- 无";

  const openSection = data.openQuestions && data.openQuestions.length > 0
    ? data.openQuestions.map((q) => `- ${q}`).join("\n")
    : "- 无";

  return `<!-- AUTO-GENERATED by SpecWave. DO NOT EDIT MANUALLY. -->
# 设计方案

> Story：${data.storyId}
> 状态：设计中

## 1. 概述

${data.overview}

## 2. 模块划分

${modulesSection}

## 3. 数据流

${data.dataFlow}

## 4. 关键决策

${decisionsSection}

## 5. 遗留问题

${openSection}
`;
}
