/**
 * Requirement Template - Code-rendered, never free-form
 * This is a CODE TEMPLATE, not a prompt template.
 * Format is guaranteed by code execution, not by AI compliance.
 */

import type { RequirementSchema } from "../schemas/requirement";

/**
 * Render requirement data to markdown.
 * AI calls this via writeDoc tool. AI never writes markdown directly.
 */
export function renderRequirement(data: RequirementSchema): string {
  const constraintsList = data.analysis.constraints.length > 0
    ? data.analysis.constraints.map((c) => `- ${c}`).join("\n")
    : "- 无";

  const acceptanceRows = data.acceptance.length > 0
    ? data.acceptance.map((a) => `| ${a.action} | ${a.expected} |`).join("\n")
    : "| 待补充 | 待补充 |";

  const resourcesList = data.resources && data.resources.length > 0
    ? data.resources.map((r) => `- ${r}`).join("\n")
    : "- 无";

  return `<!-- AUTO-GENERATED by SpecWave. DO NOT EDIT MANUALLY. -->
# ${data.title}

> Story：${data.storyId}
> 状态：需求确认中

## 1. 诉求

${data.userIntent}

## 2. 分析

### 2.1 核心问题

${data.analysis.coreProblem}

### 2.2 影响范围

${data.analysis.scope}

### 2.3 约束条件

${constraintsList}

## 3. 验收口径

| 操作 | 预期结果 |
|------|----------|
${acceptanceRows}

## 4. 参考资源

${resourcesList}
`;
}
