/**
 * Task Template - Code-rendered, never free-form
 */

import type { TaskSchema } from "../schemas/task";

export function renderTask(data: TaskSchema): string {
  const taskRows = data.tasks.length > 0
    ? data.tasks.map((t) => {
        const deps = t.dependsOn && t.dependsOn.length > 0
          ? t.dependsOn.join(", ")
          : "-";
        return `| ${t.no} | ${t.desc} | ${t.acceptance} | ${t.effort} | ${deps} |`;
      }).join("\n")
    : "| - | 待补充 | 待补充 | small | - |";

  const notes = data.executionNotes
    ? `\n## 4. 执行顺序说明\n\n${data.executionNotes}\n`
    : "";

  return `<!-- AUTO-GENERATED by SpecWave. DO NOT EDIT MANUALLY. -->
# 任务清单

> Story：${data.storyId}
> 状态：待执行

## 1. 执行前必读

1. 按表格顺序执行，不得跳序或并行
2. 每完成一项，在【状态】列标记 ✅ 并写简要说明
3. 遇到困难先标记 ⚠️ 并说明卡点，不擅自改方案
4. 全部完成后回复「任务清单已完成」

## 2. 任务项

| 编号 | 任务描述 | 验收口径 | 工作量 | 依赖 |
|------|----------|----------|--------|------|
${taskRows}
${notes}
`;
}
